### PR TITLE
Allow settings to be overridden.

### PR DESCRIPTION
**Pull request by clokep**
This allows the use of Django's `override_settings`, by not declaring setting values at import time, but lazily evaluating them from `django.conf.settings` when requested. This maintains the previous behavior that a backend is only created once, however, it is created on first use instead of at import time.

### CODE REVIEW

**Comment by lamby** [comment]
I started merging this on ``lamby/percipient-override-settings`` but then I noticed:

```
            self.assertRaises(
                RaisingBackend.RaisedException,
                slack_message('test.slack', {'text': 'test'}),
            )
```

ie. its missing a lambda. Actually I've just pushed a better version as:

```
            with self.assertRaises(RaisingBackend.RaisedException):
                slack_message('test.slack', {'text': 'test'})
```

.. but this actually means most of tests fail in a way thats not immediately obvious to me. Can you look into this? Please use ``lamby/percipient-override-settings`` as your base as I've already made a bunch of changes there. :)

**Comment by clokep** [comment]
Thanks for taking a look. Just wanted to say that this is still on my radar, but I haven't had a chance to look at this in the past few days. Will get to it soon!

**Comment by lamby** [comment]
Hey, any movement on this? :)

**Comment by clokep** [comment]
@lamby take a look at https://github.com/percipient/django-slack/commit/590a24ddf081d42437ac0071955d48224cb2f7c4

**Comment by lamby** [comment]
Nice! Could you force-push that to this PR so we can merge it? :)

**Comment by clokep** [comment]
@lamby Pushed.

**Comment by lamby** [comment]
Thank you, merged and releasing in a couple of minutes...

**Comment by clokep** [comment]
@lamby Thanks! Sorry it took so long for me to get back to this.

**Pull request merged**
