### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by Eraldo**
Based on your new branch.. I updated the backend to now work with python3.

### CODE REVIEW

**Comment by Eraldo** [comment]
Solving #12 #18 #19

**Comment by Eraldo** [comment]
@lamby: Would be awesome if you could also update the version and push the changes to pypi.

**Comment by lamby** [comment]
I'm really sorry but this still has issues that I raised in the initial PR and we have referered to at least three times this evening... eg. `items` vs `iteritems`, etc. etc

There are also lots of unrelated whitespace changes that are not appropriate here and/or not split into separate commits. 

I would also like to see a comment regarding why binary_data needs encoding there.

**Comment by Eraldo** [comment]
Tried to work in your feedback.
Did some research on the iteritems vs  items issue and added comments to explain the internal procedure.

**Comment by lamby** [comment]
>  It should be encoded to bytes before being used as the data parameter.

I'm afraid that doesn't really explain *why*, and the rest of the docstring isn't really telling us anything that useful to be honest - it just reads like a comment for a comments sake.

**Comment by Eraldo** [comment]
That is taken from the official docs of *The urllib docs say for urllib.request.Request*
https://docs.python.org/3/library/urllib.request.html#urllib.request.urlopen

I'd love to help further.. but to be honest I do not know how.
@lamby Could you please guide me?

**Comment by lamby** [comment]
Closing as fixed on master and released.

I think we have very different concepts on what counts as clean git usage - if you have other functionality or changes, please make separate pull requests - don't add extra features and/or misc changes to unrelated PRs.

**Comment by Eraldo** [comment]
I think we have similar concepts of what clean ought to be.

However I am no veteran and many things worked differently than what I intended to do..
(like auto-formatting of whitespace/newlines upon commit, etc.)
Partly due to using a new IDE.
I completely agree with your standards.. and hope to be better able to provide value in the future.

As a side note.. one think confuses me: First you tell me that you want clear documentation on why encoding happens.. then then you contradict yourself by releasing the code without a single line of documentation on this matter.
You surprise me. :D

Anyway..
Thanks for the fast responses and doing a good job.

**Pull request closed without merging**
